swagger: "2.0"
info:
  version: 2.5.0
  title: Inscription backend
  description: Backend API for webapp Edacy
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  FilmBody:
    type: object
    title: films
    required:
      - nom
      - synopsis
      - annee
      - image
      - type
      - prix

    properties:
      nom:
        type: string
        example: 24h Chrono
      synopsis:
        type: string
        example: un bon film
      annee:
        type: string
        example: 2018
      image:
        type: string
        example: Ba.jpg
      type:
        type: string
        example: Fiction
      prix:
        type: string
        example: 2500FCFA
        
  InscriptionBody:
    type: object
    title: inscriptions
    required:
      - film
    
    
  
       
paths:
  
  
  /films:
    get:
      tags:
        - Films
      description: Fetch all films
      responses:
        200:
          description: Returns all films
    post:
      tags:
        - Films
      description: Create a new Film
      parameters:
        - name: Film
          in: body
          description: an example
          required: true
          schema: 
            $ref: "#/definitions/FilmBody"
      responses:
        200:
          description: film crée
     
      
  
          description: module crée     

      

  /inscriptions:
    get:
      tags:
        - Inscriptions
      description: Fetch all Inscriptions
      responses:
        200:
          description: Returns all Inscriptions
    post:
      tags:
        - Inscriptions
      description: Create a new Inscription
      parameters:
        - name: inscription
          in: body
          description: an example
          required: true
          schema: 
            $ref: "#/definitions/InscriptionBody"
      responses:
        200:
          description: Returns all examples

  /inscription/{id}:
    get:
      tags:
        - Inscriptions
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the Inscription to retrieve
          type: integer
      responses:
        200:
          description: Return the Inscription with the specified id
        404:
          description: Inscription not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification